### PR TITLE
Closes #69

### LINKED ISSUE #69: Tests fail with OpenMPI 4.0.3
The tests t8_test_cmesh_bcast and t8_test_hypercube fail with an Comm assertion using OpenMPI 4.0.3

This needs to verified and investigated.

### PR DESCRIPTION
**Pull request by Davknapp**
Duplicating the communicator and checking for congrunence in the communicator.

### CODE REVIEW

**Comment by holke** [comment]
Thanks for this fix.

There is still a memory leak, though:

`valgrind --leak-check=full test/t8_test_bcast`
produces
```
==56078== 
==56078== HEAP SUMMARY:
==56078==     in use at exit: 152 bytes in 33 blocks
==56078==   total heap usage: 2,744 allocs, 2,711 frees, 10,466,728 bytes allocated
==56078== 
==56078== 16 bytes in 4 blocks are definitely lost in loss record 5 of 9
==56078==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==56078==    by 0x4F9D903: MPIR_Find_local_and_external (in /home/holke/tools/mpich-3.3.2/install/lib/libmpi.so.12.1.8)
==56078==    by 0x4F62894: MPIR_Comm_commit (in /home/holke/tools/mpich-3.3.2/install/lib/libmpi.so.12.1.8)
==56078==    by 0x4F63B40: MPII_Comm_copy (in /home/holke/tools/mpich-3.3.2/install/lib/libmpi.so.12.1.8)
==56078==    by 0x4E9E120: MPIR_Comm_dup_impl (in /home/holke/tools/mpich-3.3.2/install/lib/libmpi.so.12.1.8)
==56078==    by 0x4E9E4A3: PMPI_Comm_dup (in /home/holke/tools/mpich-3.3.2/install/lib/libmpi.so.12.1.8)
==56078==    by 0x10D3BC: t8_cmesh_bcast (t8_cmesh.c:982)
==56078==    by 0x111888: t8_cmesh_new_hypercube (t8_cmesh.c:2308)
==56078==    by 0x10AAA0: t8_check_bcast_hypercube (t8_test_bcast.c:31)
==56078==    by 0x10AC1A: main (t8_test_bcast.c:57)
==56078== 
==56078== 16 bytes in 4 blocks are definitely lost in loss record 6 of 9
==56078==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==56078==    by 0x4F9D91F: MPIR_Find_local_and_external (in /home/holke/tools/mpich-3.3.2/install/lib/libmpi.so.12.1.8)
==56078==    by 0x4F62894: MPIR_Comm_commit (in /home/holke/tools/mpich-3.3.2/install/lib/libmpi.so.12.1.8)
==56078==    by 0x4F63B40: MPII_Comm_copy (in /home/holke/tools/mpich-3.3.2/install/lib/libmpi.so.12.1.8)
==56078==    by 0x4E9E120: MPIR_Comm_dup_impl (in /home/holke/tools/mpich-3.3.2/install/lib/libmpi.so.12.1.8)
==56078==    by 0x4E9E4A3: PMPI_Comm_dup (in /home/holke/tools/mpich-3.3.2/install/lib/libmpi.so.12.1.8)
==56078==    by 0x10D3BC: t8_cmesh_bcast (t8_cmesh.c:982)
==56078==    by 0x111888: t8_cmesh_new_hypercube (t8_cmesh.c:2308)
==56078==    by 0x10AAA0: t8_check_bcast_hypercube (t8_test_bcast.c:31)
==56078==    by 0x10AC1A: main (t8_test_bcast.c:57)
```

File: src/t8_cmesh/t8_cmesh.c [hunk 1]
```diff
@@ -969,15 +969,19 @@ t8_cmesh_bcast (t8_cmesh_t cmesh_in, int root, sc_MPI_Comm comm)
...
     /* Root returns the input cmesh */
     cmesh_out = cmesh_in;
   }
   /* TODO: we could optimize this by using IBcast */
   mpiret = sc_MPI_Bcast (&meta_info, sizeof (meta_info), sc_MPI_BYTE, root,
                          comm);
+
+  SC_CHECK_MPI (mpiret);
+#ifdef T8_ENABLE_DEBUG
+  sc_MPI_Comm_dup (comm, &(meta_info.comm));
```
Comment (holke) [inline src/t8_cmesh/t8_cmesh.c:982]:
```suggestion
  mpiret = sc_MPI_Comm_dup (comm, &(meta_info.comm));
  SC_CHECK_MPI (mpiret);
```

File: src/t8_cmesh/t8_cmesh.c [hunk 2]
```diff
@@ -1004,7 +1008,9 @@ t8_cmesh_bcast (t8_cmesh_t cmesh_in, int root, sc_MPI_Comm comm)
         meta_info.num_trees_per_eclass[iclass];
     }
 #ifdef T8_ENABLE_DEBUG
-    T8_ASSERT (meta_info.comm == comm);
+    int                 result;
+    sc_MPI_Comm_compare (comm, meta_info.comm, &result);
```
Comment (holke) [inline src/t8_cmesh/t8_cmesh.c:1012]:
```suggestion
    mpiret = sc_MPI_Comm_compare (comm, meta_info.comm, &result);
    SC_CHECK_MPI (mpiret);
```

File: src/t8_cmesh/t8_cmesh.c [hunk 3]
```diff
@@ -1026,6 +1032,7 @@ t8_cmesh_bcast (t8_cmesh_t cmesh_in, int root, sc_MPI_Comm comm)
   cmesh_out->mpisize = mpisize;
   /* Final checks */
 #ifdef T8_ENABLE_DEBUG
+  sc_MPI_Comm_free (&meta_info.comm);
```
Comment (holke) [inline src/t8_cmesh/t8_cmesh.c:1035]:
```suggestion
  mpiret = sc_MPI_Comm_free (&meta_info.comm);
  SC_CHECK_MPI (mpiret);
```

**Review by holke — COMMENTED** [review]
Looks good to me.

All sc_MPI calls need an
```
mpiret = sc_MPI_Call(*);
SC_CHECK(mpiret);
```

I added these now by myself.

I am now checking whether it runs with OpenMPI 4.0 and if so, we can merge.

**Comment by holke** [comment]
Note: You can link issues with PRs, see the setting on the right hand side.
I linked this with #69. Meaning that closing this PR will automatically close the issue.

**Review by holke — APPROVED** [review]
Just checked this with OpenMPI 4.0.5 and the test run through :+1:
